spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritydb?serverTimezone=UTC
    username: root
    password: 250628
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8888
